.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. goldbcr_qt test_goldbcr_qt
clean: FORCE
	$(MAKE) -C .. goldbcr_qt_clean test_goldbcr_qt_clean
check: FORCE
	$(MAKE) -C .. test_goldbcr_qt_check
goldbcr-qt goldbcr-qt.exe: FORCE
	 $(MAKE) -C .. goldbcr_qt
